# Generated by Django 2.2.7 on 2019-11-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('poisonous', models.CharField(max_length=100)),
                ('maxGrowth', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=50)),
                ('light', models.CharField(max_length=50)),
                ('watering', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=200)),
                ('airHumidity', models.CharField(max_length=50)),
            ],
        ),
    ]
