# Generated by Django 2.2.7 on 2019-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.FloatField(max_length=100),
        ),
    ]
