# Generated by Django 2.2.7 on 2019-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickapp', '0002_auto_20191125_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='poisonous',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='watering',
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='maxGrowth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
