# Generated by Django 2.2.7 on 2019-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickapp', '0003_auto_20191127_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='lifespan',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='lightDuration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='toxic',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
