# Generated by Django 2.2.7 on 2019-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickapp', '0004_auto_20191127_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='match',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
